"""Stock feature generation including momentum indicators and volatility
    Currently RSI (Relative Strength Index), volatility, and price return rank are successfully calculated for each stock
    and for each day based on the basic price data ingested from yahoo. To Run the program,
    the stock_price_and_returns.csv file containing time series daily, monthly, and yearly returns
    must be generated by running the price_returns.py file and placed in the same directory.
    The output of the prgram will be an updated csv file with a new rsi and volatility column.
    TODO: percent off 52 week high, and Sharp Ratio
George Krug
04/22/2019
"""


import pandas as pd
import time
from taIndicators import momentum, basic, volatility as vol
import dataframeHandling as dfhandle
import sys


def clean_and_merge_monthly_and_yearly_dfs(df_yearly, df_monthly):
    # Convert to single index on Symbol
    df_yearly.set_index(['Symbol'], inplace=True)
    df_monthly.set_index(['Symbol'], inplace=True)

    # Drop duplicate columns to isolate monthly rankings
    try:
        df_monthly.drop(
            columns=['Open', 'High', 'Low', 'Close', 'Volume', 'AdjClose', 'Pct_Change_Daily', 'Pct_Change_Monthly',
                     'Pct_Change_Yearly', 'RSI', 'Volatility', 'Sharp_Ratio'], inplace=True)
    except Exception as err:
        pass

    # Declare Final Dataframe to be stored
    global final_df
    final_df = pd.DataFrame()

    # Loop symbol rows in dataframe and merge to add the monthly return rankings to the yearly
    for symbol in ticker_list:
        tmp = pd.merge(df_yearly.loc[symbol], df_monthly.loc[symbol], on='Date', how='inner')
        tmp['Symbol'] = symbol
        final_df = final_df.append(tmp)

    # Adjusted index before converted or stored
    try:
        final_df.reset_index(level=0, inplace=True)
        final_df['date_of_transaction']=final_df['Date']
        final_df.set_index(['Symbol', 'Date'], inplace=True)
        final_df.drop(columns=['Yearly_Return', 'Monthly_Return', 'index'], inplace=True)

    except Exception as err:
        print(err)

    return final_df


def get_index_lists(df, ticker_list, date_list):
    # Get Index Lists
    for symbol, mrow in df.groupby(level=0):
        ticker_list.append(symbol)

    for date, mrow in df.groupby(level=1):
        date_list.append(date)

    return ticker_list, date_list


def handle_input_arguments():
    """
    Handle input arguments and allow for custom test files
    :return:
    """
    if len(sys.argv) > 1:
        if sys.argv[1] == "-test" and len(sys.argv) == 2:
            return "test"
        elif sys.argv[1] == "-f" and len(sys.argv) == 3:
            return "test"
        elif (len(sys.argv) == 2 and sys.argv[1] is not "-test") or (len(sys.argv) == 3 and sys.argv[1] != "-f") or len(sys.argv) > 3:
            print("ERROR: Improper input arguments!\nDefault Test Command:"
                  " \n\tpython feature-gen.py -test\nCustom Test File Command:\n\tpython feature-gen.py -f <file name>")
            return "error"
        else:
            return "live"


###############################
# Main Method
###############################
if __name__== '__main__':
    file_path = "data/stock_prices_and_returns_3.csv"
    test_file_path = "data-test/Head_stock_prices_and_returns.csv"
    output_file_path = "data/momentum-features.csv"
    test_output_file = "data-test/test-momentum.csv"
    new_columns = ['RSI', 'Volatility', 'Sharp_Ratio']
    ticker_list = []
    date_list = []

    # Allow custom input file for testing
    action = handle_input_arguments()
    if action == "test":
        file_path = test_file_path
        output_file_path = test_output_file
    elif action == "error":
        exit(1)

    print("input file: " + file_path)
    print("output file: " + output_file_path)

    # convert csv to dataframe, index ticker & date, and add new featur columns
    #basic_df = dfhandle.get_dataframe_from_csv(file_path)
    
    max_date=dfhandle.find_max_date()
    print('max date '+max_date)
    start = time.time()
    
    basic_df=dfhandle.read_table('stock_price_return',max_date)
    basic_df['Date']=basic_df['date_of_transaction']
    end = time.time()

    df = dfhandle.add_columns_to_df(basic_df, new_columns)
    basic_df['Date']=basic_df['date_of_transaction']
    # get index lists of 3d df to optimize looping
    ticker_list, date_list = get_index_lists(df, ticker_list, date_list)

    print('Generating Momentum Features\n-------------------------------------------------------------')
    print('Updating Dataframe with RSI, Volatility, Sharp Ratio and Performance Rank columns......')
    start = time.time()
    for symbol in ticker_list:
        df = momentum.get_stock_rsi_daily(df, symbol)
        df = vol.get_stock_volatility(df, symbol)

    # Get Daily adjusted return rankings based on trailing monthly and yearly prices
    df_yearly, df_monthly = momentum.get_daily_adjusted_stock_return_rankings(df, ticker_list, date_list)

    print(df_yearly.head())
    print(df_monthly.head())

    # Clean and merge data
    final_df = clean_and_merge_monthly_and_yearly_dfs(df_yearly, df_monthly)

    ######################################################
    #  OUTPUT DATA #######################################
    print("Writing to file: " + output_file_path)
    #final_df.to_csv(output_file_path, encoding='utf-8', index=True)
    print(final_df.columns)
    final_df.reset_index()
    final_df.info()

    final_df.set_index(['ticker_y', 'date_of_transaction'], inplace=True)
    final_df.reset_index(inplace=True)

    # initialize percent change positive/negative binary
    # copy values from percent change daily before data manipulation
    final_df['Pct_Change_Class'] = final_df['Pct_Change_Daily']


    # if percent positive, assign 1; else assign 0
    final_df['Pct_Change_Class'].where(final_df['Pct_Change_Class'] < 0, other=1, inplace=True)
    final_df['Pct_Change_Class'].where(final_df['Pct_Change_Class'] > 0, other=0, inplace=True)
    final_df.head()

    # set index on symbol
    final_df.set_index('ticker_y', inplace=True)
    print(final_df.head())

    # initialize new rolling average features
    final_df['Rolling_Yearly_Mean_Positive_Days'] = final_df['Pct_Change_Class']
    final_df['Rolling_Monthly_Mean_Positive_Days'] = final_df['Pct_Change_Class']
    final_df['Rolling_Monthly_Mean_Price'] = final_df['AdjClose']
    final_df['Rolling_Yearly_Mean_Price'] = final_df['AdjClose']


    # use pandas rolling method to calculate moving averages on selected featurs on a monthly and yearly basis
    YEARLY_TRADING_DAYS = 252
    MONTHLY_TRADING_DAYS = 21
    rolling_monthly_up_days = final_df.groupby(level=0)['Rolling_Monthly_Mean_Positive_Days'].rolling(MONTHLY_TRADING_DAYS, min_periods=MONTHLY_TRADING_DAYS).mean()
    rolling_yearly_up_days = final_df.groupby(level=0)['Rolling_Yearly_Mean_Positive_Days'].rolling(YEARLY_TRADING_DAYS, min_periods=YEARLY_TRADING_DAYS).mean()
    monthly_rolling_average_price = final_df.groupby(level=0)['Rolling_Monthly_Mean_Price'].rolling(MONTHLY_TRADING_DAYS, min_periods=MONTHLY_TRADING_DAYS).mean()
    yearly_rolling_average_price = final_df.groupby(level=0)['Rolling_Yearly_Mean_Price'].rolling(YEARLY_TRADING_DAYS, min_periods=YEARLY_TRADING_DAYS).mean()


    # copy values into the working stocks dataframe
    final_df['Rolling_Monthly_Mean_Positive_Days'] = rolling_monthly_up_days.values
    final_df['Rolling_Yearly_Mean_Positive_Days'] = rolling_yearly_up_days.values
    final_df['Rolling_Monthly_Mean_Price'] = monthly_rolling_average_price.values
    final_df['Rolling_Yearly_Mean_Price'] = yearly_rolling_average_price.values


    print(final_df.head())

    print(final_df.info())

    final_df.set_index(['ticker_x', 'date_of_transaction'], inplace=True)

    final_df['Momentum_Quality_Monthly'] = (final_df['Pct_Change_Monthly'] * 100) * (( final_df['Rolling_Monthly_Mean_Positive_Days'] - (1 - final_df['Rolling_Monthly_Mean_Positive_Days'])))
    final_df['Momentum_Quality_Yearly'] = (final_df['Pct_Change_Yearly'] * 100) * (( final_df['Rolling_Yearly_Mean_Positive_Days'] - (1 - final_df['Rolling_Yearly_Mean_Positive_Days'])))


    print(final_df.head())

    spy=dfhandle.read_table('spy_stock_price_return',max_date)

    #spy.drop(columns=['Unnamed: 0'], inplace=True)

    #df.groupby(level=0)['SPY_Trailing_Month_Return'] = spy['Pct_Change_Monthly']
    spy.set_index('date_of_transaction', inplace=True)

    spy_trailing_month_return = spy.drop(columns=['sno','Symbol', 'High', 'Low', 'Open', 'Close', 'Volume', 'AdjClose', 'ticker','Pct_Change_Daily', 'Pct_Change_Yearly'])

    global spy_df
    spy_df = pd.DataFrame()
    spy_trailing_month_return['SPY_Trailing_Month_Return'] = spy_trailing_month_return['Pct_Change_Monthly']
    spy_trailing_month_return.drop(columns=['Pct_Change_Monthly'], inplace=True)

    spy_trailing_month_return.reset_index(inplace=True)
    spy_trailing_month_return.drop(columns=['Date'], inplace=True)

    print(final_df.info())

    for symbol, r in final_df.groupby(level=0):
        tmp = r
        #print("Sybmol"+symbol)
        tmp.reset_index(inplace=True)
        tick = pd.merge(tmp, spy_trailing_month_return, how='left', left_index=True, right_index=True)
        spy_df = spy_df.append(tick)
    
    
    spy_df['Symbol']=spy_df['ticker_x']
    spy_df['Date']=spy_df['date_of_transaction_x']
    spy_df.set_index(['ticker_x', 'date_of_transaction_x'], inplace=True)
    

    print(spy_df.info())

    columns=['Symbol','Date','High','Low','Open','Close','Volume','AdjClose','Pct_Change_Daily','Pct_Change_Monthly','Pct_Change_Yearly','RSI','Volatility','Yearly_Return_Rank','Monthly_Return_Rank','Rolling_Yearly_Mean_Positive_Days','Rolling_Monthly_Mean_Positive_Days','Rolling_Monthly_Mean_Price','Rolling_Yearly_Mean_Price','Momentum_Quality_Monthly','Momentum_Quality_Yearly','SPY_Trailing_Month_Return']

    print(spy_df[columns].head())

    dfhandle.load_table(spy_df[columns],'momentum_features')
    end = time.time()
    print("Process time: " + str(end - start) + " seconds.")
    ######################################################