"""Stock feature generation including momentum indicators and volatility

    Currently RSI (Relative Strength Index) and volatility are successfully calculated for each stock
    and for each day based on the basic price data ingested from yahoo. To Run the program,
    the stock_price_and_returns.csv file containing time series daily, monthly, and yearly returns
    must be generated by running the price_returns.py file and placed in the same directory.
    The output of the prgram will be an updated csv file with a new rsi and volatility column.

    TODO: percent off 52 week high, stock relative rank (based on price performance), and Sharp Ratio

George Krug
04/22/2019
"""


import pandas as pd
from talib import RSI
import matplotlib.pyplot as plt
import time


START_DATE = '2011-01-03'
END_DATE = '2019-04-03'
ROLLING_WINDOW = 30


def get_stock_rsi_daily(time_series_df, ticker):
    # compute RSI vector using ta-lib
    close = get_time_series_adjusted_close(time_series_df, ticker)
    rsi = RSI(close, timeperiod=20)
    rsi_series = pd.Series(rsi)
    # add to db data structure
    tmpDf = pd.DataFrame(data=rsi_series, columns=['RSI'])
    time_series_df.loc[ticker, 'RSI'] = tmpDf['RSI'].values
    return time_series_df


def get_stock_percent_off_52_week_high():
    pass


def get_stock_trailing_52_week_performance_rank():
    pass


def get_stock_volatility(time_series_df, ticker):
    close = get_time_series_adjusted_close(time_series_df, ticker)
    # compute Volatility with intermediate-term rolling window
    close_series = pd.Series(close)
    roller = close_series.rolling(ROLLING_WINDOW)
    vol_vec = roller.std(ddof=0)
    tmp_vol_df = pd.DataFrame(data=vol_vec, columns=['Volatility'])
    time_series_df.loc[ticker, 'Volatility'] = (tmp_vol_df['Volatility'].values / close) * 12
    return time_series_df


def get_stock_sharp_ratio():
    pass


def get_time_series_adjusted_close(time_series_df, ticker):
    return time_series_df.loc[ticker].loc[::, 'AdjClose'].values


def get_dataframe_from_csv(file):
    try:
        df = pd.read_csv(file)
    except FileNotFoundError as err:
        print("FileNotFoundError with path " + file + "\nError: " + err)
        raise
    return df


def add_columns_to_df(basic_df, columns):
    # Set Multi Index on the dataframe to get the 3d data structure
    try:
        new_df = basic_df.set_index(['Symbol', 'Date'])
    except Exception as err:
        print("index set error")
        print(err)
        raise

    # Add columns to the new df
    for col in columns:
        new_df[col] = -1

    return new_df


def main():

    print('Generating Momentum Features\n-------------------------------------------------------------')
    file_path = "stock_prices_and_returns.csv"
    output_file_path = "momentum-features.csv"
    new_columns = ['RSI', 'Volatility']

    basic_df = get_dataframe_from_csv(file_path)
    df = add_columns_to_df(basic_df, new_columns)

    print('Updating Dataframe with RSI values......')
    start = time.time()
    for symbol, mrow in df.groupby(level=0):
        print(symbol)
        df = get_stock_rsi_daily(df, symbol)
        df = get_stock_volatility(df, symbol)

    print("Writing to file: " + output_file_path)
    df.to_csv(output_file_path, encoding='utf-8', index=True)
    end = time.time()
    print("Process time: " + str(end - start) + " seconds.")


if __name__ == '__main__':
    main()
